version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for Node.js dependencies
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      all:
        patterns:
          - "*"

    commit-message:
      prefix: "chore(deps):"